id: AA4247B7F
base_file: fA856.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:52:41.722758
  last_modified_at: 2022-06-17 12:52:41.722761
