id: AA4247B7F
base_file: f3A7E.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:52:41.721443
  last_modified_at: 2022-06-17 12:52:41.721448
