id: AA4247B7F
base_file: f17AC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:52:41.718233
  last_modified_at: 2022-06-17 12:52:41.718240
